### PR TITLE
chore: bump `monocart-coverage-reports`

### PR DESCRIPTION
**Pull request by cenfun**

### CODE REVIEW

**Comment by mrazauskas** [comment]
Thanks! Hm.. Looks like merging is still not working.

Can I ask why `json` and `js` files got included? 

https://github.com/tstyche/tstyche/blob/1f07bc64c81953a80fe984a7694d19a267f7c12a/scripts/report-coverage.js#L28-L32

**Comment by cenfun** [comment]
Thank you for the reminder, I think I know the reason now. seems the source filter is not working for untested files. WIP

**Comment by mrazauskas** [comment]
Thanks! Reports for each platform look right. All is good there. But merged report is still odd:

Screenshot 2024-09-16 at 12 58 34

Previously it looked like this:

Screenshot 2024-09-16 at 13 00 10

Hm.. Somethings is simply off in the Uncovered column? Or?

**Comment by cenfun** [comment]
I found the file path is defferent when merging the raw with downloaded artifacts (win/mac/linux)
Still testing ...

**Comment by mrazauskas** [comment]
Should be something else. Did you notice that only Bytes and Lines are incorrectly counted in the merged report? All is fine with Statements, Branches and Functions.

**Comment by mrazauskas** [comment]
Hooray! That simple.

Screenshot 2024-09-16 at 15 54 36

---

I can take over from here. Don’t worry about that formatting issue. Thanks for your time!

**Pull request merged**
